site_name: Tensor Layers
repo_url: https://github.com/bpiwowar/TensorOperators.jl
repo_name: GitHub
site_author: Benjamin Piwowarski
site_description: TensorOperators - Building Blocks for Neural Networks

theme: journal

pages:
- [index.md, Home]
- [modules.md, Layers, Introduction]
- [containers.md, Layers, Containers]
- [linear.md, Layers, Linear]
- [transfer.md, Layers, Transfer]
- [classification.md, Layers, Classification]
- [cost.md, Cost]
- [optimization.md, Optimization]

markdown_extensions:
    fenced_code:
    meta:
